# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
mixed-port: 7890

# Port of HTTP(S) proxy server on the local end
port: 7891

# Port of SOCKS5 proxy server on the local end
socks-port: 7892

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7893

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7894

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
# bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: true

# RESTful web API listening address
external-controller: 0.0.0.0:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: ui/

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Menual GeoData custom url
geox-url:
  geoip: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  geosite: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/Country.mmdb"


proxy-groups:
  - name: PROXY
    type: select
    use:
      - mine
      - dongchengjie
      - dedyn-vless
      - dedyn-vmess
      - chromego
      - shunfeng
####################################################################################################
proxy-providers:
  mine:
    type: http
    url: 'https://raw.githubusercontent.com/tony-sung/clash-meta-configuration/main/subscription/mine.yaml'
    interval: 1800
    path: subscription/mine.yaml
    health-check:
      enable: true
      interval: 900
      url: 'http://www.gstatic.com/generate_204'

  dongchengjie:
    type: http
    url: 'https://raw.githubusercontent.com/dongchengjie/airport/main/subs/dongchengjie.yaml'
    interval: 1800
    path: subscription/dongchengjie.yaml
    health-check:
      enable: true
      interval: 900
      url: 'http://www.gstatic.com/generate_204'

  dedyn-vless:
    type: http
    url: 'https://vless.fxxk.dedyn.io/auto'
    interval: 1800
    path: subscription/dedyn-vless.yaml
    health-check:
      enable: true
      interval: 900
      url: 'http://www.gstatic.com/generate_204'

  dedyn-vmess:
    type: http
    url: 'https://vmess.fxxk.dedyn.io/auto'
    interval: 1800
    path: subscription/dedyn-vmess.yaml
    health-check:
      enable: true
      interval: 900
      url: 'http://www.gstatic.com/generate_204'

  chromego:
    type: http
    url: 'https://mareep.netlify.app/sub/merged_proxies_new.yaml'
    interval: 1800
    path: subscription/chromego.yaml
    health-check:
      enable: true
      interval: 900
      url: 'http://www.gstatic.com/generate_204'

  shunfeng:
    type: http
    url: 'https://shunfeng.2424014450.workers.dev/'
    interval: 1800
    path: subscription/shunfeng.yaml
    health-check:
      enable: true
      interval: 900
      url: 'http://www.gstatic.com/generate_204'

####################################################################################################
rules:
  - GEOIP,lan,DIRECT,no-resolve
  - GEOIP,cn,DIRECT,no-resolve
  - GEOSITE,category-ads-all,REJECT
  - DOMAIN,www.bing.com,PROXY
  - DOMAIN,sydney.bing.com,PROXY  
  - GEOSITE,category-dev,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,cn,DIRECT
  - MATCH,PROXY
